#-------------------------------
# General Site Settings
baseurl: "/galada" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com


#-------------------------------
# About Section
name: DevelopersPoint
title: DevelopersPoint | Developers Point
description: DevelopersPoint is an open source student run club
tags:
  - blog
  - developerspoint
  - opensource
  - studentclub
  - nitap


#-------------------------------
# Contact links
facebook:  https://facebook.com/developerspoint-org # Add your Facebook handle
twitter:   https://twitter.com/developerspoint-org # Add your Facebook handle
instagram: https://www.instagram.com/developerspoint-org # Add your Facebook handle
pinterest: https://www.pinterest.com/developerspoint-org # Add your Facebook handle
github_username: developerspoint-org
facebook_username: developerspoint-org
twitter_username: developerspoint-org
instagram_username: developerspoint-org
linkedin_username: developerspoint-org
medium_username: developerspoint-org

#-------------------------------
# Comment Section (Disqus)
email: contact@developerspoint.org
disqus-identifier: developerspoint-org


#-------------------------------
# Instagram Feed
instafeed: true # To enable the instafeed, use the value true. To turn off use the value false.


#-------------------------------
# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1.


#-------------------------------
# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e


# Advanced Settings
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://blog.developerspoint.org/" # the base hostname & protocol for your site
google_analytics: "UA-XXXXXXXX-X"
language: "en"
categories_folder: category
sent_message_url: "/contact/message-sent/"


#-------------------------------
# Build settings
markdown: kramdown
permalink: ':title/'
plugins:
  - jekyll-paginate
  - jekyll-sitemap

paginate: 7
paginate_path: "/page/:num"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed


#-------------------------------
# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
